# Generated by Django 6.0.2 on 2026-07-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.TextField(max_length=800)),
                ('technologies', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('project_link', models.URLField()),
                ('display_order', models.IntegerField(default=0)),
            ],
        ),
    ]
