# Generated by Django 6.0.2 on 2026-07-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_institution', models.CharField(max_length=50)),
                ('start_year', models.IntegerField()),
                ('finish_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
