# Generated by Django 6.0.2 on 2026-07-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=50)),
                ('place_of_work', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('work_description', models.TextField(max_length=400)),
            ],
        ),
    ]
