# Generated by Django 6.0.2 on 2026-07-24 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='finish_date',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='start_date',
        ),
    ]
