# Generated by Django 6.0.2 on 2026-07-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='position_held_at_work',
            field=models.CharField(default='waitress', max_length=50),
            preserve_default=False,
        ),
    ]
