# Generated by Django 6.0.2 on 2026-07-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_experience_position_held_at_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me_description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_name', models.CharField(max_length=100)),
                ('issuing_institution', models.CharField(max_length=100)),
                ('date_of_issue', models.DateField()),
                ('gained_skills', models.CharField(blank=True, null=True)),
                ('certification_description', models.TextField(max_length=1000)),
                ('credential_ID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.TextField(max_length=2000)),
                ('creators', models.CharField(blank=True, max_length=200, null=True)),
                ('used_tools', models.TextField(max_length=500)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('project_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('skill_category', models.CharField(choices=[('Cognitive skills', 'Cognitive skills'), ('Technical skills', 'Technical skills'), ('Creative skills', 'Creative skills'), ('Managment skills', 'Managment skills')])),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_role', models.CharField(max_length=100)),
                ('institution_name', models.CharField(max_length=100)),
                ('volunteering_start_date', models.DateField()),
                ('volunteering_finish_date', models.DateField()),
                ('description_of_volunteering', models.TextField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='education',
            name='name_of_institution',
        ),
        migrations.AddField(
            model_name='education',
            name='institution_name',
            field=models.CharField(default='Uniwersytet Komisji Edukacji Narodowej w Krakowie', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='employer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='place_of_work',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position_held_at_work',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='work_description',
            field=models.TextField(max_length=1000),
        ),
    ]
